### ISSUE TITLE
Can target exe execute first then execute the bat file second?

### ISSUE THREAD

**Issue by jamborloi** [npocmaka/batch.scripts#1]
Can I use this to execute the exe first (ex. putty.exe) then execute the .bat next?

**Comment by npocmaka** [comment]
Hello jamborloi .  Which bat do you mean?

~best regards.

**Comment by jamborloi** [comment]
Hey Thanks for the reply...Actually you got a good tool https://github.com/npocmaka/batch.scripts/blob/master/hybrids/iexpress/bat2exeIEXP.bat

in IEXPRESS wizard in windows I usually used to add to package 2 .exe file. One is install file and the other is post installation command. 

I understand your comman for this batch file is bat2exeIEXP.bat  myBatFile.bat MyExecutable.exe
how can I do it with it will do the install program first like putty.exe first then the post install command will be a powershell.bat.
![image](https://cloud.githubusercontent.com/assets/8010075/12287876/ddbaee68-ba0a-11e5-803a-228449c52e44.png)

**Comment by npocmaka** [comment]
As I understand your question - you want to pack in one exe  putty and one powershell.bat and then to execute the bat file?

**Comment by npocmaka** [comment]
here's an example SED file where you will need to change the paths:
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\target\exewithputty.exe
FriendlyName=jamborloi
AppLaunched=cmd /c powershell.bat
PostInstallCmd=
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="putty.exe"
FILE1="powershell.bat"
[SourceFiles]
SourceFiles0=C:\sources
[SourceFiles0]
%FILE0%=
%FILE1%=
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

and then you can create the package with iexpress /n /q /m sedfile.sed

**Comment by jamborloi** [comment]
Hi, thank you for this I have tried and attached below,
And came out error creating process. Putty did not came out as well. However that launcher.bat which is powershell command serve its purpose correctly.
![image](https://cloud.githubusercontent.com/assets/8010075/12298110/63415a64-ba4b-11e5-86d4-d8ddbca06399.png)
