### ISSUE TITLE
pinnerJS does not work windows 10 pro

### ISSUE THREAD

**Issue by Owned67** [npocmaka/batch.scripts#14]
`call pinnerJS.bat Regshot.exe startmenu
`
return 

> pinning Regshot.exe to start menu

Regshot is not pinned
not in folder %AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\StartMenu
not in C:\ProgramData\Microsoft\Windows\Start Menu
not in C:\ProgramData\Microsoft\Windows\Start Menu\Programmes

Thanks for fix

**Comment by npocmaka** [comment]
check this - https://stackoverflow.com/a/38880235/388389  - I'll have to rewrite it for windows 10 and this will take me some time.

**Comment by Owned67** [comment]
too complicated for me... Thanks I'l wait...

**Comment by Owned67** [comment]
I have found a solution with classic shell, thanks.
