### ISSUE TITLE
mouse.bat positions dont work

### ISSUE THREAD

**Issue by travick** [npocmaka/batch.scripts#15]
I'm using windows 10 and the screen res is 1600x900

position arg returns correct XxY co-ordinates
but moveTo doesn't move exactly like the co-ordinates provided.

I need to enter 65000x65000 to reach (moveTo) near the bottom-right corner.

**Comment by npocmaka** [comment]
i'll take a look in a few hours. I hope it is not an emergency case.

**Comment by npocmaka** [comment]
This should fix it:
 https://stackoverflow.com/questions/8021954/sendinput-doesnt-perform-click-mouse-button-unless-i-move-cursor  - later it will be added.

**Comment by npocmaka** [comment]
@travick  - can you try it now? And thanks for pointing this out.
