### ISSUE TITLE
zipjs.bat -> zipitem fails for files ("file doesn't exist" when it clearly does.)

### ISSUE THREAD

**Issue by JavidPack** [npocmaka/batch.scripts#2]
Should the zipItem argument really call the ZipDirItems command?

https://github.com/npocmaka/batch.scripts/blob/master/hybrids/jscript/zipjs.bat#L796

and should the ZipItem command fail if the source isn't a folder?

https://github.com/npocmaka/batch.scripts/blob/master/hybrids/jscript/zipjs.bat#L491

**Comment by npocmaka** [comment]
I think you've found a 2 serious bugs in my code :+1: I'll update the script and will credit you

**Comment by npocmaka** [comment]
updated.
