### ISSUE TITLE
Speedup optimisation for .net batch files

### ISSUE THREAD

**Issue by SergeAgeyev** [npocmaka/batch.scripts#22]
Absolutely great job!

Just one suggestion to speedup operation in .net bat files:
Add `if exist "%~n0.exe" %~n0.exe %*` just after begin of bath body, so it will not search for .net framework if to compile .net part if it is already compiled (if compiled .exe exists, it will run it immediately):

Was:
```
:batch
@echo off
setlocal
```

Faster:
```
:batch
@echo off
if exist "%~n0.exe" %~n0.exe %*
setlocal
```

**Comment by npocmaka** [comment]
Very good idea! When I have the time I'll update the .net hybrids.

**Comment by SergeAgeyev** [comment]
More detailed and better solution is in issue #25
