### ISSUE TITLE
zipjs.bat > Unzip checks if source is a valid folder, where it should be destination

### ISSUE THREAD

**Issue by Hooglander1** [npocmaka/batch.scripts#3]
In line 549 it should be changed from (source) to (destination). We do not want to check if the source is a proper folder, but the destination. Now unzipping fails on all commands.

Tried it locally and that fixed the issue.

**Comment by npocmaka** [comment]
Hello and thanks for the comment.
Line 549 is correct - it checks if the source is folder from the Shell.Application point of view.It is the same as opening a zip file with the explorer.exe (May be I should left a comment at the function definition). In the next line is checked if there's file or folder existing on the destination and if the option is force it will be deleted. Probably you are trying to unzip a lot of times in a folder that already exist and it's deleted?  I think I should add option that will unzip in folder without deleting it...

If this is the case you can consider unzipping in different folders and later merge them with copy command.

You can also create a feature request and I'll try to add unzipping in existing folder function in next two or three weeks .

Best regards.
