### ISSUE TITLE
Print several times

### ISSUE THREAD

**Issue by Lieven150** [npocmaka/batch.scripts#7]
Thanks, works brilliantly! Is it possible to get some documents to print in twofold, threefold, ... ?

**Comment by npocmaka** [comment]
@Lieven150 - hello.  I'm not sure what's the request here... What script have you used (printJS.bat?)?  You want to print documents resized?Or several times?  

best regards.

**Comment by Lieven150** [comment]
Hi, yes, print some documents several times. E.g. 5 docs in the folder: print 1-3 one time, and print 4 & 5 three times.

**Comment by npocmaka** [comment]
you can create simple bat file (or if you prefer powershell...) that can do this . Here is an example repeatPrints.bat (must be in the same folder as printJS.bat):

```
@echo off
set "file_to_print=%~f1"
set /a "copies=%~2"

for /l %%# in (1;1;%copies%) do (
  call  printJS.bat "%file_to_print%"
)
```

and you can use it like `repeatPrints.bat "c:\docs\myFile.pdf" 5` which will print it 5 times.

**Comment by Lieven150** [comment]
thanks, super!
