### ISSUE TITLE
in system\monitorInfo.bat file opener is missing

### ISSUE THREAD

**Issue by GijonDev** [npocmaka/batch.scripts#8]
In between `endlocal` and `del ~.txt /q /f >nul 2>nul`, **`~.txt`** is missing. On its current state, the file won't open any file. Also, adding `if EXIST` in the first deletion command would make everything cleaner.

Final state of the file:

`@echo off`
_**`if EXIST ~.txt del ~.txt /q /f >nul 2>nul`**_
`start "" /w dxdiag /t ~`
`setlocal enableDelayedExpansion`
`set currmon=1 `
`for /f "tokens=2 delims=:" %%a in ('find "Current Mode:" ~.txt') do (`
	`echo Monitor !currmon! : %%a`
	`set /a currmon=currmon+1`

`)`
`endlocal `
_**`~.txt`**_
`del ~.txt /q /f >nul 2>nul`

I would have opened a pull request but I have no idea on how to do it.

**Comment by npocmaka** [comment]
The idea is the result to be printed in the console. In the ~.txt there's a lot of information that probably you'll never need. Though if you prefer to see the file itself for sure you can use the modified version.
